### PR TITLE
Added GattCharacteristic1 MTU support

### PR DESCRIPTION
**Pull request by robbym**
Issue: https://github.com/bluez-rs/bluez-async/issues/131
btleplug: https://github.com/deviceplug/btleplug/issues/246

### CODE REVIEW

**Review by qwandor — APPROVED** [review]
Thanks!

**Comment by laxian** [comment]
@qwandor @robbym This PR is not in the latest version: 0.7.2

**Comment by qwandor** [comment]
@laxian I have now released `bluez-generated` 0.4.0 including this change.

**Comment by laxian** [comment]
Thank you! @qwandor. I noticed that bluez-generated 0.4.0 is released.
I'm not sure if this PR supports MTU query or MTU negotiation.

**Pull request merged**
