### PR TITLE
[bluez-generated] Add more BlueZ interfaces and methods.

### PR DESCRIPTION
**Pull request by GreenDjango**
Hi,
I run `introspect.sh` on my laptop:
```
Fedora 36
Kernel 6.0.11
systemd v250.8
bluez 5.66
```
I found new interfaces and methods, but I don't included all deprecated properties from `org.bluez.MediaControl1`.

The fmt also change due to my `rustfmt` version 1.5.1.

### CODE REVIEW

**Comment by qwandor** [comment]
Thanks for the PR!

The introspection file changes look fine. It looks like you've got a bunch of other changes to the generated code, perhaps due to a different version of  `dbus-codegen`, which is causing our CI to fail. Could you stick with `dbus-codegen` 0.9.1 for this PR, and then if you want to update to the latest version that can be a separate PR? When you do so, you'll need to update [.github/workflows/lint.yml](https://github.com/bluez-rs/bluez-async/blob/main/.github/workflows/lint.yml#L9) to match.

**Comment by GreenDjango** [comment]
I don't see a Rust action setup in the lint CI.
Rust is already provide by ubuntu-latest ?

**Comment by qwandor** [comment]
Yeah, not sure what version but it seems to work.

**Comment by qwandor** [comment]
Merged. Do you want a release now, or do you have other changes in mind first?

**Comment by GreenDjango** [comment]
Thanks!
Yes, I'm going to add more `DeviceInfo` properties like:
 - alias
 - class
- icon
- trusted
- blocked
- legacy_pairing
- modalias

Do you think is a great idea to add  `set_alias` or `set_blocked` in `DeviceInfo` ?

**Comment by qwandor** [comment]
Okay, I'll wait for that then.

`DeviceInfo` just holds information about a device and doesn't have a reference back to the service to set anything. If you want to add methods to set things then they will need to be on `BluetoothSession`.

**Pull request merged**
